//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPLETE_FLAT_UI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_perdida
    {
        public int id { get; set; }
        public Nullable<int> id_perdida { get; set; }
        public Nullable<decimal> costo_unitario { get; set; }
        public Nullable<int> idProducto { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual producto producto { get; set; }
        public virtual perdida perdida { get; set; }
    }
}
