//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPLETE_FLAT_UI.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PuntoDeVentaEntities : DbContext
    {
        public PuntoDeVentaEntities()
            : base("name=PuntoDeVentaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cState> cState { get; set; }
        public virtual DbSet<detalle_entrada> detalle_entrada { get; set; }
        public virtual DbSet<detalle_perdida> detalle_perdida { get; set; }
        public virtual DbSet<detalle_venta> detalle_venta { get; set; }
        public virtual DbSet<entrada> entrada { get; set; }
        public virtual DbSet<perdida> perdida { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<venta> venta { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
    }
}
